### ISSUE TITLE
Circulating Supply Endpoint: 500 Internal Server Error

### ISSUE THREAD

**Issue by chriscollinsgit** [threshold-network/token-supply-endpoint#7]
The following endpoint

https://api.threshold.network/supply/t

is returning the following error

500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

Let me know if you need any further information

**Comment by derekpierre** [comment]
Thanks for filing.

https://status.nucypher.network/supply_information?q=est_circulating_supply, which the endpoint uses was down, and caused the 500. It is now back up and running.
